

export const CLASSES_LOADING_START ="LOADING_START";
export const CLASSES_SUCCESS = "CLASSES_SUCCESS";
export const CLASSES_ERROR = "CLASSES_ERROR";
export const INIT_CLASSES  ="INIT_CLASSES";

export const LECTURE_LOADING_START ="LECTURE_LOADING_START";
export const LECTURE_SUCCESS = "LECTURE_SUCCESS";
export const LECTURE_ERROR = "LECTURE_ERROR";
export const LECTURE_INIT  ="LECTURE_INIT";

export const QUESTIONS_LOADING_START ="QUESTIONS_LOADING_START";
export const QUESTIONS_SUCCESS = "QUESTIONS_SUCCESS";
export const QUESTIONS_ERROR = "QUESTIONS_ERROR";
export const QUESTIONS_INIT  ="QUESTIONS_INIT";

export const POST_QUESTIONS_LOADING_START ="POST_QUESTIONS_LOADING_START";
export const POST_QUESTIONS_SUCCESS = "POST_QUESTIONS_SUCCESS";
export const POST_QUESTIONS_ERROR = "POST_QUESTIONS_ERROR";
export const POST_QUESTIONS_INIT  ="POST_QUESTIONS_INIT";
export const NULLIFY_SUCCESS_POST_QUESTION = "NULLIFY_SUCCESS_POST_QUESTION";


export const FORGET_PASSWORD_LOADING_START ="FORGET_PASSWORD_LOADING_START";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const FORGET_PASSWORD  ="FORGET_PASSWORD";

export const REGISTER_LOADING_START ="REGISTER_LOADING_START";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const POST_REGISTER  ="POST_REGISTER";


export const AUTH_LOADING          = "AUTH_LOADING"
export const AUTH_SUCCESS          = "AUTH_SUCCESS"
export const AUTH_FAIL             = "AUTH_FAIL"
export const AUTH_INI_LOGOUT       = "AUTH_INI_LOGOUT"
export const AUTO_LOGOUT           = "AUTO_LOGOUT"
export const AUTH_FALSIFY_REDIRECT = "AUTH_FALSIFY_REDIRECT";
export const CHECK_EXPIRY          = "CHECK_EXPIRY";
export const POST_AUTH             = "POST_AUTH";
export const AUTH_CHECK_STATE      = "AUTH_CHECK_STATE";

export const ACTIVATION            = "ACTIVATION";
export const ACTIVATION_LOADING    = "ACTIVATION_LOADING";
export const ACTIVATION_ERROR      = "ACTIVATION_ERROR";
export const ACTIVATION_SUCCESS    = "ACTIVATION_SUCCESS";

export const RESET_LOADING_START   = "RESET_LOADING_START";
export const RESET_SUCCESS         = "RESET_SUCCESS";
export const RESET_ERROR           = "RESET_ERROR";
export const RESET                 = "RESET";


export const ANSWER            = "ANSWER";
export const ANSWER_LOADING    = "ANSWER_LOADING";
export const ANSWER_ERROR      = "ANSWER_ERROR";
export const ANSWER_SUCCESS    = "ANSWER_SUCCESS";
export const ANSWER_UPDATE     = "ANSWER_UPDATE";
export const LATEST_ANSWER     = "LATEST_ANSWER";

export const STATUS            = "STATUS";
export const STATUS_LOADING    = "STATUS_LOADING";
export const STATUS_ERROR      = "STATUS_ERROR";
export const STATUS_SUCCESS    = "STATUS_SUCCESS";


export const NOTIFICATION            = "NOTIFICATION";
export const NOTIFICATION_LOADING    = "NOTIFICATION_LOADING";
export const NOTIFICATION_ERROR      = "NOTIFICATION_ERROR";
export const NOTIFICATION_SUCCESS    = "NOTIFICATION_SUCCESS";



export const PERCENTAGE            = "PERCENTAGE";
export const PERCENTAGE_LOADING    = "PERCENTAGE_LOADING";
export const PERCENTAGE_ERROR      = "PERCENTAGE_ERROR";
export const PERCENTAGE_SUCCESS    = "PERCENTAGE_SUCCESS";